<?php

/**
 * Implements hook_menu()
 */
function osci_tk_search_menu() {
	$items = array();
	$items['api/search'] = array(
		'title' 			=> t('Search'),
		'page callback' 	=> 'osci_tk_search_query',
		'type' 				=> MENU_CALLBACK,
		'access arguments'  => array('access content'),
	);
	$items['api/opensearch'] = array(
		'title' 			=> t('Search'),
		'page callback' 	=> 'osci_tk_search_opensearch_query',
		'type' 				=> MENU_CALLBACK,
		'access arguments'  => array('access content'),
	);
	$items['admin/config/search/opensearch'] = array(
	  	'title' 			=> t('Open Search Settings'),
	  	'page callback' 	=> 'drupal_get_form',
	  	'page arguments' 	=> array('osci_tk_search_opensearch'),
	  	'access arguments' 	=> array('administer site configuration'),
	  	'file' 				=> 'osci_tk_search.admin.inc',
	);
	$items['opensearch/document'] = array(
		'title'				=> t('OpenSearch Document'),
		'page callback'		=> 'osci_tk_search_display_opensearch_document',
		'access arguments'  => array('access content'),
		'type'				=> MENU_CALLBACK,
	);
	return $items;
}

/**
 * Implements hook_theme().
 */
function osci_tk_search_theme($existing, $type, $theme, $path) {
	return array(
		'opensearch_description' => array(
			'variables' => array(),
			'template' 	=> 'templates/opensearch-description',
			'file' 		=> 'osci_tk_search.templates.inc'
		),
		'opensearch_results' => array(
			'variables' => array(
				'response' => NULL,
			),
			'template'	=> 'templates/opensearch-results',
			'file'		=> 'osci_tk_search.templates.inc'
		),
	);
}

/**
 * Generate basic search results as JSON
 */
function osci_tk_search_query() {
	$response = osci_tk_search_do_query();
	print json_encode($response);
}

/**
 * Generates open search results 
 */
function osci_tk_search_opensearch_query() {
	$response = osci_tk_search_do_query();
	print theme('opensearch_results', array('response' => $response));
}

/**
 * Perform primary query
 * @return Object
 */
function osci_tk_search_do_query() {
	// setup query parameters
	$params['q']	= arg(2);
	$params['fl']	= 'label, url, teaser';
	$solrsort		= '';
	$filters 		= isset($_GET['filters']) ? $_GET['filters'] : '';

	$query = apachesolr_drupal_query('oscitk', $params, $solrsort);
	$query->page = pager_find_page();
	// add content boost parameters to the query
	apachesolr_search_add_boost_params($query);
	// execute query
	list($final_query, $response) = apachesolr_do_query($query, $query->page);
	return $response->response;
}

/**
 * Display the OpenSearch document
 */
function osci_tk_search_display_opensearch_document() {
	print theme('opensearch_description');
}

/**
 * Implements hook_apachesolr_index_document_build()
 */
function osci_tk_search_apachesolr_index_document_build(ApacheSolrDocument $document, $entity, $entity_type, $env_id) {
	switch($entity->type) {
		case 'section':
			_osci_tk_search_get_path_hierarchy($entity->book, $document);
			break;
	}
}

/**
 * Generate content path
 * @param  Object             $book     The book object
 * @param  ApacheSolrDocument $document The solr document
 */
function _osci_tk_search_get_path_hierarchy($book, ApacheSolrDocument $document) {
	// retrieve the books menu tree
	$subtree_data = array_pop(book_menu_subtree_data($book));
	// generate the content path tree
	$tree_hierarchy = array_reverse(_osci_tk_search_generate_content_path_tree($subtree_data['link']));
	
	$current_path = '';
	foreach($tree_hierarchy as $key => $path) {
		$current_path .= '/' . $path;
		// add paths to the solr document
		$document->addField('sm_path_hierarchy', $current_path);
		$document->addField('sm_path_hierarchy_depth', $key . $current_path);
	}
}

/**
 * Generate the content path hierachy
 * @param  object $link         The current link object
 * @param  array $content_path An array of paths
 * @return array
 */
function _osci_tk_search_generate_content_path_tree($link, $content_path = null) {
	// set initial path
	if(!$content_path) {
		$content_path[$link['depth'] - 1] = _osci_tk_search_clean_title($link['title']);
	}
	// check to see if the section is already at the root
	if($link['depth'] <= 1) return $content_path;

	// load the book link
	$parent_link = book_link_load($link['plid']);
	$content_path[$parent_link['depth'] - 1] = _osci_tk_search_clean_title($parent_link['title']);
	// continue to obtain the parent links
	if($parent_link['depth'] > 1) {
		$content_path = _osci_tk_search_generate_content_path_tree($parent_link, $content_path);
	}
	return $content_path;
}

/**
 * Replaces title spacing with hyphens
 * @param  string $title Book/section title
 * @return string
 */
function _osci_tk_search_clean_title($title) {
	return str_replace(' ', '-', $title);
}