<?php

function osci_tk_webapp_preview_menu() {
    $items['admin/config/system/osci/webapp'] = array(
        'title'             => t('Web App'),
        'description'       => 'Settings for the OSCI Toolkit Web App',
        'page callback'     => 'drupal_get_form',
        'page arguments'    => array('osci_tk_webapp_admin_form'),
        'access arguments'  => array('administer OSCI ToolKit settings'),
        'type'              => MENU_LOCAL_TASK,
        'file'              => 'osci_tk_webapp.admin.inc',
    );

    $items['node/%node/web-app'] = array(
		'title'             => 'OSCI Toolkit Web-App Preview',
		'page callback'     => 'osci_tk_webapp_preview',
		'page arguments'    => array(1),
		'access callback'  => '_osci_tk_webapp_preview_access',
		'access arguments'    => array(1),
		'type'              => MENU_LOCAL_TASK
    );

    $items['node/%node/web-app/nav'] = array(
    	'title'             => 'OSCI Toolkit Web-App Nav',
		'page callback'     => 'osci_tk_webapp_preview_nav',
		'page arguments'    => array(1),
		'access callback'  => '_osci_tk_webapp_preview_access',
		'access arguments'    => array(1),
		'type'              => MENU_LOCAL_TASK
    );

    return $items;
}

function osci_tk_webapp_preview_theme() {

	global $base_url;
	$basePath = variable_get('osci_tk_webapp_base_path', '');

	return array(
		'osci_tk_webapp_preview' => array(
			'variables' => array(
				'package_path' => NULL,
				'section_id' => null,
				'js' => array(),
				'css' => array(),
				'endPoints' => array(
					'OsciTkNote' => variable_get('osci_tk_webapp_note_endpoint', ''),
					'OsciTkSearch' => variable_get('osci_tk_webapp_search_endpoint', ''),
					'OsciTkOpenSearch' => variable_get('osci_tk_webapp_opensearch_endpoint', ''),
					'OsciTkAccount' => variable_get('osci_tk_webapp_account_endpoint', ''),
					'OsciTkCitation' => variable_get('osci_tk_webapp_citation_endpoint', ''),
				),
				'templatePath' => $basePath . 'js/oscitk/templates/',
				'customTemplatePath' => variable_get('osci_tk_webapp_template_path', ''),
				'toolbarItems' => variable_get('osci_tk_webapp_toolbar_items', ''),
				'sectionView' => variable_get('osci_tk_webapp_section_view', ''),
				'sectionViewOptions' => variable_get('osci_tk_webapp_section_view_options', ''),
				'paragraphControls' => variable_get('osci_tk_webapp_paragraph_controls',''),
				'basePath' => $basePath,
				'baseUrl' => $base_url
			),
			'template'  => 'templates/osci-tk-webapp-preview',
		),
	);
}

function osci_tk_webapp_preview_nav($node) {
	global $base_url;

	$pubNid = $node->nid;
	$treeData = osci_tk_nodetree_get_data_for_nid($node->nid);
	if (count($treeData) && isset($treeData[0]['rootNid'])) {
		$pubNid = $treeData[0]['rootNid'];
	}

	$output = _osci_tk_epub_generate_navigation_document($node, false, false, null, true);
	print $output;
	drupal_exit();
}

function osci_tk_webapp_preview($node) {
    global $base_url;

	$pubNid = $node->nid;
	$treeData = osci_tk_nodetree_get_data_for_nid($node->nid);
	if (count($treeData) && isset($treeData[0]['rootNid'])) {
		$pubNid = $treeData[0]['rootNid'];
	}

	if (isset($_GET['_escaped_fragment_'])) {
		$sectionNid = substr($_GET['_escaped_fragment_'], strrpos($_GET['_escaped_fragment_'], '/') + 1);
		$output = osci_tk_epub_render($sectionNid, $pubNid, true);

		$tocLink = l("Table of Contents", "node/{$pubNid}/web-app/nav");

		$parts = split("</body>", $output);
		$output = $parts[0] . $tocLink . $parts[1];

		print $output;
		drupal_exit();
	}

    $packageUri = url('api/epub/' . $pubNid . '/package.opf');

    drupal_static_reset('drupal_add_js');
	drupal_static_reset('drupal_add_css');

    $preprocessJs = variable_get("preprocess_js", 1);
    $preprocessCss = variable_get("preprocess_css", 1);

    if ($preprocessJs) {
	    $basePath = DRUPAL_ROOT . '/' . variable_get('osci_tk_webapp_base_path', '');
    } else {
        $basePath = $base_url . variable_get('osci_tk_webapp_base_path', '');
    }

	//Add the JS files
	$js = array();
	$js[] = $basePath . "js/external/json2.js";
	$js[] = $basePath . "js/external/jquery.js";
	$js[] = $basePath . "js/external/jquery.qtip.js";
	$js[] = $basePath . "js/external/lodash.js";
	$js[] = $basePath . "js/external/backbone.js";
	$js[] = $basePath . "js/external/backbone-super.js";
	$js[] = $basePath . "js/external/fancybox/jquery.fancybox.js";
	$js[] = $basePath . "js/external/polymaps.min.js";
	$js[] = $basePath . "js/external/jquery-ui/jquery-ui.min.js";
	$js[] = $basePath . "js/oscitk/osci_tk_layered_image.js";
	$js[] = $basePath . "js/oscitk/OsciTk.js";
	$js[] = $basePath . "js/oscitk/TemplateManager.js";
	$js[] = $basePath . "js/oscitk/models/BaseModel.js";
	$js[] = $basePath . "js/oscitk/models/ConfigModel.js";
	$js[] = $basePath . "js/oscitk/models/PackageModel.js";
	$js[] = $basePath . "js/oscitk/models/FigureModel.js";
	$js[] = $basePath . "js/oscitk/models/FootnoteModel.js";
	$js[] = $basePath . "js/oscitk/models/NavigationItemModel.js";
	$js[] = $basePath . "js/oscitk/models/NoteModel.js";
	$js[] = $basePath . "js/oscitk/models/SearchResultModel.js";
	$js[] = $basePath . "js/oscitk/models/AccountModel.js";
	$js[] = $basePath . "js/oscitk/models/PageModel.js";
	$js[] = $basePath . "js/oscitk/models/SectionModel.js";
	$js[] = $basePath . "js/oscitk/models/GlossaryTermModel.js";
	$js[] = $basePath . "js/oscitk/collections/BaseCollection.js";
	$js[] = $basePath . "js/oscitk/collections/FiguresCollection.js";
	$js[] = $basePath . "js/oscitk/collections/NavigationItemsCollection.js";
	$js[] = $basePath . "js/oscitk/collections/FootnotesCollection.js";
	$js[] = $basePath . "js/oscitk/collections/NotesCollection.js";
	$js[] = $basePath . "js/oscitk/collections/PagesCollection.js";
	$js[] = $basePath . "js/oscitk/collections/SearchResultsCollection.js";
	$js[] = $basePath . "js/oscitk/collections/GlossaryTermsCollection.js";
	$js[] = $basePath . "js/oscitk/views/BaseView.js";
	$js[] = $basePath . "js/oscitk/views/AppView.js";
	$js[] = $basePath . "js/oscitk/views/SectionView.js";
	$js[] = $basePath . "js/oscitk/views/PageView.js";
	$js[] = $basePath . "js/oscitk/views/MultiColumnSectionView.js";
	$js[] = $basePath . "js/oscitk/views/MultiColumnPageView.js";
	$js[] = $basePath . "js/oscitk/views/MultiColumnFigureView.js";
	$js[] = $basePath . "js/oscitk/views/MultiColumnFigureImageView.js";
	$js[] = $basePath . "js/oscitk/views/MultiColumnFigureLayeredImageView.js";
	$js[] = $basePath . "js/oscitk/views/TitleView.js";
	$js[] = $basePath . "js/oscitk/views/ToolbarView.js";
	$js[] = $basePath . "js/oscitk/views/ToolbarItemView.js";
	$js[] = $basePath . "js/oscitk/views/NavigationView.js";
	$js[] = $basePath . "js/oscitk/views/SearchView.js";
	$js[] = $basePath . "js/oscitk/views/NotesView.js";
	$js[] = $basePath . "js/oscitk/views/InlineNotesView.js";
	$js[] = $basePath . "js/oscitk/views/CitationView.js";
	$js[] = $basePath . "js/oscitk/views/FootnotesView.js";
	$js[] = $basePath . "js/oscitk/views/FiguresView.js";
	$js[] = $basePath . "js/oscitk/views/GlossaryView.js";
	$js[] = $basePath . "js/oscitk/views/GlossaryTooltipView.js";
	$js[] = $basePath . "js/oscitk/views/TocView.js";
	$js[] = $basePath . "js/oscitk/views/AccountView.js";
	$js[] = $basePath . "js/oscitk/views/FontView.js";
	$js[] = $basePath . "js/oscitk/views/ParagraphControlsView.js";
	$js[] = $basePath . "js/oscitk/Router.js";
	$js[] = $basePath . "js/oscitk/helper.js";
	$js[] = $basePath . "js/appBootstrap.js";
	$js[] = $basePath . "js/oscitk/zotero.js";

	//Add the CSS files
    if ($preprocessCss) {
        $cssBasePath = variable_get('osci_tk_webapp_base_path', '');
        if (strpos($cssBasePath, "/") === 0) {
            $cssBasePath = substr($cssBasePath, 1);
        }
    } else {
        $cssBasePath = $base_url . '/' . variable_get('osci_tk_webapp_base_path', '');
    }

	$css = array();
	$css[] = $cssBasePath . "js/external/jquery-ui/jquery-ui.min.css";
	$css[] = $cssBasePath . "js/external/jquery.qtip.css";
	$css[] = $cssBasePath . "js/external/fancybox/jquery.fancybox.css";
	$css[] = $cssBasePath . "css/common.css";
	$css[] = $cssBasePath . "css/toolbar.css";
	$css[] = $cssBasePath . "css/section.css";
	$css[] = $cssBasePath . "css/multiColumnSection.css";
	$css[] = $cssBasePath . "css/search.css";
	$css[] = $cssBasePath . "css/navigation.css";
	$css[] = $cssBasePath . "css/notes.css";
	$css[] = $cssBasePath . "css/glossary.css";
	$css[] = $cssBasePath . "css/layered_image.css";
	$css[] = $cssBasePath . "css/citation.css";
	$css[] = $cssBasePath . "css/themeNight.css";
	$css[] = $cssBasePath . "css/themeSepia.css";

	drupal_alter("osci_tk_webapp_custom", $js, $css);

	if ($preprocessJs) {
		$finalJs = array();
		foreach($js as $jsFile) {
			$finalJs[$jsFile] = array(
				"data" => $jsFile,
				"preprocess" => true
			);
		}
		$js = array(file_create_url(drupal_build_js_cache($finalJs)));
	}

	if ($preprocessCss) {
		$finalCss = array();
		foreach($css as $cssFile) {
			$finalCss[$cssFile] = array(
				"data" => $cssFile,
				"preprocess" => true,
				"type" => "file"
			);
		}

		$css = array(file_create_url(drupal_build_css_cache($finalCss)));
	}

    print theme('osci_tk_webapp_preview', array(
    	'package_path' => $packageUri,
    	'section_id' => ($pubNid === $node->nid) ? null : $node->nid,
    	'js' => $js,
    	'css' => $css
    ));

    drupal_exit();
}

function _osci_tk_webapp_preview_access($node) {
	if ($node->type === 'publication') {
		return true;
	} else {
		return false;
	}
}

function osci_tk_webapp_preview_nodetree_navigation_link($treeData) {
	return array(l('WebApp Preview', 'node/' . $treeData['rootNid'] . '/web-app', array('fragment' => 'section/' . $treeData['nid'])));
}

function _osci_tk_webapp_create_url($sectionNid, $revTime, $pubNid) {
	return url('node/' . $pubNid . '/web-app', array(
		'fragment' => 'section/' . $sectionNid,
		'absolute' => true,
        'query' => array(
            'revision' => $revTime
        )
    ));
}
