<?php

/***********************************************************************
 *
 * Drupal Hooks
 *
 */

function osci_tk_filters_init() {
    drupal_add_js(libraries_get_path('fancybox').'/fancybox/jquery.fancybox-1.3.4.js', array('weight' => '5'));
    drupal_add_css(libraries_get_path('fancybox').'/fancybox/jquery.fancybox-1.3.4.css');
    drupal_add_js(drupal_get_path('module', 'osci_tk_filters').'/js/osci_tk_filters.js', array('weight' => '5'));
    drupal_add_css(drupal_get_path('module', 'osci_tk_filters').'/css/osci_tk_filters.css');
    $settings = array(
        'osci_tk_filters' => array(
            'modulePath' => base_path().drupal_get_path('module', 'osci_tk_filters'),
			'current_nid' => arg(1)
        ),
    );
    drupal_add_js($settings, 'setting');
}

function osci_tk_filters_theme()
{
    return array(
        'osci_tk_figure_link' => array(
            'template'  => 'templates/osci_tk_figure_link',
            'variables' => array(
                'section'   => NULL,
                'figure'    => NULL,
                'fig_index' => NULL,
                'fig_id'    => null,
                'fig_text'  => null
            )
        ),
        'osci_tk_footnote_link' => array(
            'template'  => 'templates/osci_tk_footnote_link',
            'variables' => array(
                'footnote_id' => NULL,
                'footnote_index' => null
            )
        ),
    );
}

/**
 * Implementation of hook_filter_info
 */
function osci_tk_filters_filter_info() {
    $filters = array();

    // Footnotes
    $filters['osci_tk_footnote_reference'] = array(
        'title'             => t('Footnote Reference filter'),
        'description'       => t('Add references to footnotes in content'),
        'process callback'  => '_filter_footnote',
        'settings callback' => '_filter_settings',
        'tips callback'     => '_filter_footnote_tips',
		'cache'				=> false
    );

    $filters['osci_tk_figure'] = array(
        'title'             => t('Figure filter'),
        'description'       => t('Add figures to the content inline'),
        'process callback'  => '_filter_figure',
        'settings callback' => '_filter_settings',
        'tips callback'     => '_filter_figure_tips',
		'cache'				=> false
    );

    $filters['osci_tk_figure_reference'] = array(
        'title'             => t('Figure Reference filter'),
        'description'       => t('Add references to figures in content'),
        'process callback'  => '_filter_figure_reference',
        'settings callback' => '_filter_settings',
        'tips callback'     => '_filter_figure_reference_tips',
        'cache'             => false
    );
    
    $filters['osci_tk_cross_link'] = array(
        'title'             => t('Cross Link filter'),
        'description'       => t('Allow cross content linking within a book'),
        'process callback'  => '_filter_cross_link',
        'settings callback' => '_filter_settings',
        'tips callback'     => '_filter_cross_link_tips',
		'cache'				=> false
    );

    $filters['osci_tk_clean_content'] = array(
        'title'             => t('Clean Content'),
        'description'       => t('Remove encoded html entities and replace with proper characters.'),
        'process callback'  => '_filter_clean_content',
        'settings callback' => '_filter_settings',
        'tips callback'     => '_filter_clean_content_tips',
        'cache'             => false
    );

    return $filters;
}

/**
 * Implementation of hook_wysiwyg_plugin
 */
function osci_tk_filters_wysiwyg_plugin($editor, $version) {
    switch($editor) {
        case 'ckeditor':
            return array(
                'osci_tk_filters' => array(
                    'path'      => drupal_get_path('module', 'osci_tk_filters').'/js',
                    'buttons'   => array(
                        'footnote_reference'  => t('OSCI - Footnote Reference'),
                        'figure_reference'    => t('OSCI - Figure Reference'),
                        'figure'              => t('OSCI - Figure'),
                    ),
                    'load'      => TRUE,
                ),
            );
            break;
    }
}

/**
 * Empty settings function, seems to be required by hook_filter_info
 */
function _filter_settings() {}

/***********************************************************************
 *
 * FOOTNOTE
 *
 */

/**
 * Process callback for filter
 */
function _filter_footnote($text, $filter, $format) {
	global $osci_tk_view_mode;
	
	$osci_tk_view_mode = isset($osci_tk_view_mode) ? $osci_tk_view_mode : 'full';
    $theme = 'osci_tk_footnote_link__' . $osci_tk_view_mode;

    $filtered = $text;
    $regex = '/\[footnoteref:(fn-\d+-(\d+))\]/i';
    $matches = array();
    preg_match_all($regex, $text, $matches);
    foreach ($matches[0] as $index => $match) {
        $replace = theme($theme, array(
            'footnote_id'       => $matches[1][$index],
            'footnote_index'    => $matches[2][$index]
        ));
        $filtered = str_replace($match, $replace, $filtered);
    }

    return $filtered;
}

/**
 * Tooltip funcion
 */
function _filter_footnote_tips() {
    return t('Insert a footnote with [footnoteref:ID]');
}

/***********************************************************************
 *
 * FIGURE
 *
 */

function _filter_figure($text, $filter, $format) 
{
	global $osci_tk_view_mode, $osci_tk_placed_figures;

	$osci_tk_view_mode = isset($osci_tk_view_mode) ? $osci_tk_view_mode : 'default';

    $theme = 'osci_tk_figure_formatter__' . $osci_tk_view_mode;
    $filtered = $text;

    //place these figures inline without reference
    $regex = '/\[figure:(fig-(\d+)-(\d+))\]/i';
    $matches = array();
    $osci_tk_placed_figures = is_array($osci_tk_placed_figures) ? $osci_tk_placed_figures : array();
    preg_match_all($regex, $text, $matches);
    foreach ($matches[0] as $index => $match) {
        $args = _osci_tk_filter_process_args($matches[1][$index]);
        $section_id = $matches[2][$index];
        $fig_index = $matches[3][$index];
        $section_node = node_load($section_id);

        if ($section_node) {
            if (isset($section_node->field_figure['und'][$fig_index])) {
                $figure = $section_node->field_figure['und'][$fig_index];
                $osci_tk_placed_figures[] = $fig_index;
                $figure['delta'] = $fig_index;
                $figure['fig_id'] = _osci_tk_figure_create_id($section_id, $fig_index);
                $figure['number_template'] = _osci_tk_figure_process_number_template($figure);
                $figure['export'] = $osci_tk_view_mode === 'epub' ? true : false;

                $markup = theme($theme, array(
                    'item' => $figure
                ));
                $filtered = str_replace($match, $markup, $filtered);
            }
        }
    }

    return $filtered;
}

function _filter_figure_tips() {
    return t('Insert a figure with [figure:ID]');
}


/***********************************************************************
 *
 * FIGURE Reference
 *
 */

function _filter_figure_reference($text, $filter, $format) 
{
    global $osci_tk_view_mode, $osci_tk_placed_figures;

    $osci_tk_view_mode = isset($osci_tk_view_mode) ? $osci_tk_view_mode : 'default';

    $filtered = $text;

    //place a figure reference for these figures
    $theme = 'osci_tk_figure_link__' . $osci_tk_view_mode;
    $regex = '/\[figureref:(fig-(\d+)-(\d+))\]/i';
    $matches = array();
    preg_match_all($regex, $text, $matches);
    foreach ($matches[0] as $index => $match) {
        $args = _osci_tk_filter_process_args($matches[1][$index]);
        $section_id = $matches[2][$index];
        $fig_index = $matches[3][$index];
        $section_node = node_load($section_id);
        if ($section_node) {
            if (isset($section_node->field_figure['und'][$fig_index])) {
                $figure = $section_node->field_figure['und'][$fig_index];
                $figure['delta'] = $fig_index;
                $markup = theme($theme, array(
                    'section'   => $section_node, 
                    'figure'    => $section_node->field_figure['und'][$fig_index],
                    'fig_index' => $fig_index,
                    'fig_id'    => _osci_tk_figure_create_id($section_id, $fig_index),
                    'fig_text'  => _osci_tk_figure_process_number_template($figure)
                ));
                $filtered = str_replace($match, $markup, $filtered);
            }
        }
    }

    return $filtered;
}

function _filter_figure_reference_tips() {
    return t('Insert a figure reference with [figureref:ID]');
}
/************** INSERT OTHER FILTER FUNCTIONS HERE ********************/


/***********************************************************************
 *
 * HELPER FUNCTIONS
 *
 */

/*
 * @param $text
 * A string of text with arguments
 * @return
 * A keyed array with id and args
 */
function _osci_tk_filter_process_args($text) {
    $data = array();
    $temp = explode('|', $text);
    if (isset($temp[0])) {
        $data['id'] = $temp[0];
    }
    
    if (isset($temp[1])) {
        $args = explode(',', $temp[1]);

        foreach ($args as $val) {
            $arg = explode('=', $val);
            if (isset($arg[0]) && isset($arg[1])) {
                $data['args'][$arg[0]] = $arg[1];
            }
        }
    }

    return $data;
}

/***********************************************************************
 *
 * Cross linking
 *
 */

/**
 * Process callback for filter
 */
function _filter_cross_link($text, $filter, $format) {
	global $osci_tk_view_mode;
	
	$osci_tk_view_mode = isset($osci_tk_view_mode) ? $osci_tk_view_mode : 'default';
	$result = module_invoke_all('osci_tk_filter_cross_link_' . $osci_tk_view_mode, $text, $filter, $format);
	return is_array($result) && count($result) ? $result[0] : $text;
}

function osci_tk_filters_osci_tk_filter_cross_link_default($text, $filter, $format)
{
    $regex = '/\[link:(.*?)\]/i';

    return preg_replace_callback($regex, '_process_cross_link', $text);
}

/**
 * Regex replace callback
 */
function _process_cross_link($text) {
    if (empty($text[1])) return $text[0];
    $args = _osci_tk_filter_process_args($text[1]);

    $nid = $args['id'];
    $url = url("node/{$nid}/reader");
    $linkText = isset($args['args']['text']) ? $args['args']['text'] : "Link " . $nid;
    
    $query = "";
    if (isset($args['args']['paragraph'])) {
        $query = "#para-" . $args['args']['paragraph'];
    }
    
    if (isset($args['args']['section'])) {
        $query = '#field_' . $args['args']['section'] . '_anchor';
    }
    
    if ($query) {
        $url = url("node/{$nid}/reader", array('fragment' => substr($query, 1)));
        $query = "data-query=\"$query\"";
    }

    return "<a href=\"{$url}\" class=\"cross-link\" target=\"_blank\" data-nid=\"{$nid}\" {$query}>{$linkText}</a>";
}

/**
 * Tooltip funcion
 */
function _filter_cross_link_tips() {
    return t('Insert a Link with [link:Node ID]');
}

/***********************************************************************
 *
 * Clean Content
 *
 */

/**
 * Process callback for filter
 */
function _filter_clean_content($text, $filter, $format) 
{
    return str_replace("&rsquo;", "&#8217", $text);

    return html_entity_decode($text, ENT_QUOTES, 'UTF-8');
}



/**
 * Tooltip funcion
 */
function _filter_clean_content_tips() {
    return null;
}