<?php

/**
 * Implementation of hook_perm
 */

function osci_tk_note_permission() {
    return array(
        'view own notes' => array(
            'title' => t('View own notes'),
        ),
        'create note' => array(
            'title' => t('Create Notes'),
        ),
        'administer notes' => array(
            'title' => t('Administer notes'),
        ),
    );
    
}

/**
 * Implementation of hook_init
 */
function osci_tk_note_init() {
    drupal_add_css(drupal_get_path('module', 'osci_tk_note').'/css/osci_tk_note.css');
    drupal_add_library('system', 'jquery.form');
    drupal_add_library('system', 'drupal.ajax');
    drupal_add_js(libraries_get_path('jquery-tmpl').'/jquery.tmpl.js');
    drupal_add_js(drupal_get_path('module', 'osci_tk_note').'/js/jquery.osci.note.js');
}

/**
 * Implementation of hook_menu
 */
function osci_tk_note_menu() {
    $items = array();

    $items['admin/structure/note/manage'] = array(
        'title'             => t('Note Admin'),
        'description'       => t('Administer notes'),
        'page callback'     => 'osci_tk_note_admin',
        'access arguments'  => array('administer notes'),
    );

    $items['note/%note'] = array(
        'title callback'    => 'osci_tk_note_page_title',
        'title arguments'   => array(1),
        'page callback'     => 'osci_tk_note_page_view',
        'page arguments'    => array(1),
        'access callback'   => 'osci_tk_note_access',
        'access arguments'  => array('view', 1),
        'type'              => MENU_CALLBACK,
    );

    $items['note/%note/view'] = array(
        'title' => 'View',
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => -10,
    );

    $items['note/%note/edit'] = array(
        'title'             => t('Edit'), 
        'page callback'     => 'drupal_get_form',
        'page arguments'    => array('osci_tk_note_form', 1),
        'access callback'   => 'osci_tk_note_access',
        'access arguments'  => array('create', 1),
        'type'              => MENU_LOCAL_TASK,
    );

    $items['ajax/note/add'] = array(
        'title'             => t('Add a new note'),
        'page callback'     => 'osci_tk_note_ajax_add',
        'access arguments'  => array('create note'),
        'file'              => 'osci_tk_note.ajax.inc',
    );

    $items['ajax/note/edit/%'] = array(
        'title'             => t('Edit note'),
        'page callback'     => 'osci_tk_note_ajax_add',
        'page arguments'    => array(3),
        'access arguments'  => array('create note'),
        'file'              => 'osci_tk_note.ajax.inc',
    );

    $items['ajax/note/load/%'] = array(
        'page callback'     => 'osci_tk_note_ajax_load',
        'page arguments'    => array(3),
        'access arguments'  => array('view own notes'),
        'type'              => MENU_CALLBACK,
        'file'              => 'osci_tk_note.ajax.inc',
    );

    $items['ajax/note/save'] = array(
        'page callback'     => 'osci_tk_note_ajax_save',
        'page arguments'    => array(3),
        'access arguments'  => array('create note'),
        'type'              => MENU_CALLBACK,
        'file'              => 'osci_tk_note.ajax.inc',
    );

    $items['ajax/note/delete/%'] = array(
        'page callback'     => 'osci_tk_note_ajax_delete',
        'page arguments'    => array(3),
        'access arguments'  => array('create note'),
        'type'              => MENU_CALLBACK,
        'file'              => 'osci_tk_note.ajax.inc',
    );

    $items['ajax/note/%node'] = array(
        'page callback'     => 'osci_tk_user_notes_ajax',
        'page arguments'    => array(2),
        'access callback'   => true,
        'type'              => MENU_CALLBACK,
        'file'              => 'osci_tk_note.ajax.inc',
    );

    $items['ajax/citation'] = array(
        'page callback'     => 'osci_tk_citation_ajax',
        'access callback'   => true,
        'type'              => MENU_CALLBACK,
        'file'              => 'osci_tk_note.ajax.inc',
    );

    return $items;
}

function osci_tk_note_admin() {
    return t('Choose "manage fields" or "manage display" to begin');
}

/** 
 * implementation of hook_theme
 */
function osci_tk_note_theme() {
    $items = array();

    $items['note'] = array(
        'variables' => array(
            'note'  => NULL, 
            'view_mode' => 'full',
        ),
        'template'  => 'note',
        'file'  => 'osci_tk_note.templates.inc',
    );

    return $items;
}

/**
 * Implementation of hook_entity_info
 */
function osci_tk_note_entity_info() {
    $note = array();

    $note['note'] = array(
        'label'             => t('Note'),
        'controller class'  => 'NoteEntityController',
        'base table'        => 'note',
        'fieldable'         => TRUE,
        'uri_callback'      => 'osci_tk_note_uri',
        'entity keys'       => array(
            'id' => 'onid',
        ),
        'view modes'        => array(
            'full' => array(
                'label'             => t('Full Note'),
                'custom settings'   => FALSE,
            ),
        ),
        'bundles' => array(
            'note' => array(
                'label' => t('Note'),
                'admin' => array(
                    'path' => 'admin/structure/note/manage',
                    'access arguments'  => array('administer notes'),
                ),
            ),
        ),
    );

    return $note;
}

function osci_tk_note_uri($note) {
    return array(
        'path' => 'note/' . $note->onid,
    );
}

function osci_tk_note_page_title($onid) {
    return $onid;
}

function osci_tk_note_access($op, $onid) {
    return entity_get_controller('note')->access($op, $onid);
}
/** 
 * Save a note
 * @param $note
 * The note object to save
 *
 * @return Returns the saved note object
 */
function osci_tk_note_save($note) {
    return entity_get_controller('note')->save($note);
}

/** 
 * Load a note
 *
 * @param $onid
 * The note id to load
 *
 * @param $condition
 * Obtional sql cinditions to include
 *
 * @param $reset
 * Set to true to invalidate the object cache
 *
 * @return the note object
 */
function osci_tk_note_load($onid, $conditions = array(), $reset = FALSE) {
    $onid = (is_numeric($onid)) ? array($onid) : $onid;
    $notes = entity_load('note', $onid, $conditions, $reset);

    return $notes;
}

function osci_tk_note_delete($onid) {
    return entity_get_controller('note')->delete($onid);
}

function osci_tk_note_view($note, $view_mode = 'full') {
    $note = entity_get_controller('note')->view($note, $view_mode);
    return $note;
}

function osci_tk_note_page_view($note) {
    return entity_get_controller('note')->build($note);
}

function osci_tk_note_form($form, &$form_state) {

    global $user;
    $note = $form_state['note'];

    $form['body'] = array(
        '#title'            => t('Notes'),
        '#type'             => 'textarea',
        '#default_value'    => $note->body
    );

    $form['uid'] = array(
        '#type'  => 'hidden',
        '#value' => $user->uid,
    );

    $form['selection'] = array(
        '#type'  => 'hidden',
    );

    $form['nid'] = array(
        '#type'  => 'hidden',
    );

    $form['end_node'] = array(
        '#type'  => 'hidden',
    );

    $form['end_offset'] = array(
        '#type'  => 'hidden',
    );

    $form['paragraph_id'] = array(
        '#type'  => 'hidden',
    );

    $form['parent_offset'] = array(
        '#type'  => 'hidden',
    );

    $form['start_node'] = array(
        '#type' => 'hidden',
    );

    $form['start_offset'] = array(
        '#type' => 'hidden',
    );

    $form['submit'] = array(
        '#type'  => 'submit',
        '#value' => t('Save'),
    );

    if (is_object($note)) {
        $form['onid'] = array(
            '#type'  => 'hidden',
            '#value' => $note->onid,
        );

        $form['paragraph_count']['#value']  = $note->paragraph_count;
        $form['original_text']['#value']    = $note->original_text;
        $form['letter_count']['#value']     = $note->letter_count;
        $form['word_count']['#value']       = $note->word_count;
        $form['nid']['#value']              = $note->nid;
    }

    field_attach_form('note', $note, $form, $form_state);

    return $form;
}

function osci_tk_note_form_validate($form, &$form_state) {
    $note = (object) $form_state['values'];
    field_attach_form_validate('note', $note, $form, $form_state);
}

function osci_tk_note_form_submit($form, &$form_state) {
    $note = (object)$form_state['values'];

    field_attach_submit('note', $note, $form, $form_state);
    if ($note = note_save($note) && !$form_state['ajax']) {
        $form_state['redirect'] = 'note/'.$note->onid;
        drupal_set_message('Successfully saved note');
    }
}

function osci_tk_citation_form() {
    $form = array();

    $items = array(
        l('Chicago', $_GET['q'], array(
            'fragment' => 'citation-format-default', 
        )),
//        l('APA', $_GET['q'], array(
//            'fragment' => 'citation-format-apa', 
//        )),
        l('MLA', $_GET['q'], array(
            'fragment' => 'citation-format-mla', 
        )),
//        l('Chicago', $_GET['q'], array(
//            'fragment' => 'citation-format-chicago', 
//        )),
    );
    $format_links = theme('item_list', array('items' => $items)); 

    $form['citation_options'] = array(
        '#type'     => 'item',
        '#title'    => t('Format'),
        '#markup'   => $format_links,
    );

    $form['citation_text'] = array(
        '#markup'   => '<div id="citation_text"></div>',
    );    

    $form['citation_url'] = array(
        '#type'     => 'textfield',
        '#title'    => 'Paragraph URL',
    );

    $form['citation_selection'] = array(
        '#markup'   => '<span id="citation_paragraph_text_label">Paragraph Text</span><div id="citation_paragraph_text"></div>'
    );

    $form['citation_helper'] = array(
        '#type'     => 'item',
        '#markup'   => t('Select text and press <strong>ctrl + c</strong> to copy'),
    );

    return $form;
}

function osci_tk_note_preprocess_osci_viewer(&$vars) {
    global $user;
    
    ctools_include('modal');
    ctools_modal_add_js();
    drupal_add_js(array(
        'fixed-modal' => array(
            'modalSize' => array(
                'type'      => 'fixed',
                'width'     => 500,
                'height'    => 350,
            ),
        ),
        'citation-modal' => array(
            'modalSize' => array(
                'type'      => 'fixed',
                'width'     => 500,
                'height'    => 500,
            ),
        ),
    ), 'setting');

    
    
    $items = array();
//        l('Highlight', $_GET['q'], 
//            array(
//                'fragment' => 'note-highlight', 
//                'attributes' => array(
//                    'class' => array('note-highlight'),
//                )
//            )
//        ),
    
    if ($user->uid) 
    {
        $items[] = l('Note', 'ajax/note/add', 
            array(
                'attributes' => array(
                    'class' => array('ctools-use-modal', 'ctools-modal-fixed-modal'),
                )
            )
        );
    }
    
    
    $items[] = l('Cite', 'ajax/citation',
        array(
            'attributes' => array(
                'class' => array('ctools-use-modal', 'ctools-modal-citation-modal'),
            ),
        )
    );

    $vars['notes'] = theme('item_list', 
        array(
            'items' => $items, 
            'attributes' => array(
                'class' => 'selection-toolbar'
            )
        )
    );
}

function osci_tk_user_notes($node) {
    global $user;
    $rows = null;
    
    $query = db_select('note', 'c')
        ->fields('c')
        ->condition('uid', $user->uid)
        ->condition('nid', $node->nid)
        ->execute();
    foreach($query as $row) {
        $rows[] = (array)$row; 
    }

    return $rows;

}

function osci_tk_note_form_alter(&$form, &$form_state, $form_id)
{
    switch($form_id) 
    {
        case "note_form":
            unset($form['field_taxonomy_tags']['und']['#autocomplete_path']);
            break;
    }
}
