<?php

function osci_tk_citations_menu() {
	$items = array();

	$items['citations'] = array(
		'title'			 	=> t('Process a citation request'),
		'page callback'	 	=> 'osci_tk_citations_request',
		'access callback'	=> TRUE
	);

	$items['citations/demo'] = array(
		'title'			 	=> t('Demonstrate Citation Functionality'),
		'page callback'		=> 'drupal_get_form',
		'page arguments' 	=> array('osci_tk_citations_demo'),
		'access callback'	=> TRUE
	);

	return $items;
}

function osci_tk_citations_request() {
	if (isset($_GET['section_id']) && !empty($_GET['section_id'])
		&& isset($_GET['paragraph_id']) && !empty($_GET['paragraph_id'])) {
		
		$sid = $_GET['section_id'];
		$pid = $_GET['paragraph_id'];
		
		// load the section node and its book-parent section. if no parent, use itself
		$section = node_load($sid);
		$book_section = isset($section->book['bid']) 
			? node_load($section->book['bid']) 
			: $section;
		
		// for missing values on the section, inherit from the book-parent section
		if (!isset($section->author) && empty($section->author) && isset($book->author)) {
			$section->author = $book->author;
		}
		if (!isset($section->publisher) && empty($section->publisher) && isset($book->publisher)) {
			$section->publisher = $book->publisher;
		}
		if (!isset($section->publication_date) && empty($section->publication_date) && isset($book->publication_date)) {
			$section->publication_date = $book->publication_date;
		}
		if (!isset($section->editor) && empty($section->editor) && isset($book->editor)) {
			$section->editor = $book->editor;
		}
		
		// output the json response
		print json_encode(array(
			'success' => TRUE, 
			'citation' => array(
				'author' 			=> $section->author,
				'section_title' 	=> $section->title,
				'book_title' 		=> $book_section->title,
				'publisher' 		=> $section->publisher,
				'paragraph' 		=> $pid,
				'publication_date' 	=> $section->publication_date,
				'editor' 			=> $section->editor,
				'url'				=> ""
			)
		));
		return;
	}
	else {
		print json_encode(array('success' => FALSE));
	}
}

function osci_tk_citations_demo() {
	global $user;
	drupal_add_js(drupal_get_path('module', 'osci_tk_citations') . '/js/demo.js');

	$form = array();

	$form['retrieve'] = array(
		'#type'				=> 'fieldset',
		'#title'			=> 'Retrieve Citation Data',
		'#attributes'		=> array('class' => array('retrieve-form'))
	);
	$form['retrieve']['section_id'] = array(
		'#type'				=> 'textfield',
		'#title'			=> 'Section id',
	);
	$form['retrieve']['paragraph_id'] = array(
		'#type'				=> 'textfield',
		'#title'			=> 'Paragraph id',
	);
	$form['retrieve']['submit'] = array(
			'#type'			=> 'button',
			'#title'		=> 'Paragraph id',
			'#value'		=> 'Submit',
			'#required'		=> TRUE
	);
	$form['retrieve']['result'] = array(
			'#type'			=> 'item',
			'#title'		=> 'Result',
			'#markup'		=> '<pre style="width: 600px;"><div id="ret-result"></div></pre>'
	);

	return $form;
}