<?php

function osci_tk_users_menu() {
	$items = array();

	$items['api/users'] = array(
		'title'			 	=> t('Process a user request'),
		'page callback'	 	=> 'osci_tk_users_request',
		'access callback'	=> TRUE
	);

	$items['api/users/demo'] = array(
		'title'			 	=> t('Demonstrate User API'),
		'page callback'		=> 'drupal_get_form',
		'page arguments' 	=> array('osci_tk_users_demo'),
		'access callback'	=> TRUE
	);

	return $items;
}

function osci_tk_users_request() {
	global $user;
	dpm($_REQUEST);
	if (isset($_REQUEST['action'])) {
		// operate based on action
		switch($_REQUEST['action']) {
			case 'login':
				// check requirements
				if (!isset($_POST['username']) || !isset($_POST['password'])) {
					_osci_tk_users_json_error('username and password required');
				}
				// check for inactive or blocked user
				if (user_is_blocked($_POST['username'])) {
					_osci_tk_users_json_error('user has not been activated or is blocked');
				}
				// attempt to log in
				$uid = user_authenticate($_POST['username'], $_POST['password']);
				if ($uid > 0) {
					$user = user_load($uid);
					user_login_finalize();
					_osci_tk_users_json_success();
				}
				else { 
					_osci_tk_users_json_error('authentication failed for this user and pass');
				}
				break;
				
			case 'register':
				// check requirements are present
				if (!isset($_POST['username']) || !isset($_POST['password']) || !isset($_POST['email'])) {
					_osci_tk_users_json_error('username, password, and email are required');
				}
				// check that the requirements are well formed
				$error = user_validate_name($_POST['username']);
				if ($error) {
					_osci_tk_users_json_error($error);
				}
				$error = user_validate_mail($_POST['email']);
				if ($error) {
					_osci_tk_users_json_error($error);
				}
				// test if user or email already exist
				$count = db_query('SELECT name FROM {users} u WHERE u.name = :name', 
					array(':name' => $_POST['username']))
					->rowCount();
				if ($count > 0) {
					_osci_tk_users_json_error('username is not unique');
				}
				$count = db_query('SELECT mail FROM {users} u WHERE u.mail = :mail', 
					array(':mail' => $_POST['email']))
					->rowCount();
				if ($count > 0) {
					_osci_tk_users_json_error('email is not unique');
				}
				// create the user
				$account = new stdClass();
				$account->is_new = TRUE;
				$account->status = 1;
				$account->name = $_POST['username'];
				$account->mail = $_POST['email'];
				user_save($account, array('pass' => $_POST['password']));
				_osci_tk_users_json_success();
				drupal_exit();
				break;
				
			default:
				_osci_tk_users_json_error('action not recognized');
		} 
	}
	else {
		// no action provided
		_osci_tk_users_json_error('missing action');
	}
}

function osci_tk_users_demo() {
	global $user;
	drupal_add_js(drupal_get_path('module', 'osci_tk_users') . '/js/demo.js');

	$form = array();

	$form['login'] = array(
		'#type'			=> 'fieldset',
		'#title'		=> 'Login',
		'#attributes'	=> array('class' => array('login-form'))
	);
	$form['login']['username'] = array(
		'#type'			=> 'textfield',
		'#title'		=> 'Username',
	);
	$form['login']['password'] = array(
		'#type'			=> 'textfield',
		'#title'		=> 'Password',
	);
	$form['login']['submit'] = array(
		'#type'			=> 'button',
		'#value'		=> 'Submit',
		'#required'		=> TRUE
	);
	$form['login']['result'] = array(
		'#type'			=> 'item',
		'#title'		=> 'Result',
		'#markup'		=> '<pre style="width: 600px;"><div id="login-result"></div></pre>'
	);
	
	$form['register'] = array(
		'#type'			=> 'fieldset',
		'#title'		=> 'Register',
		'#attributes'	=> array('class' => array('register-form'))
	);
	$form['register']['username'] = array(
		'#type'			=> 'textfield',
		'#title'		=> 'Username',
	);
	$form['register']['password'] = array(
		'#type'			=> 'textfield',
		'#title'		=> 'Password',
	);
	$form['register']['email'] = array(
		'#type'			=> 'textfield',
		'#title'		=> 'Email Address',
	);
	$form['register']['submit'] = array(
		'#type'			=> 'button',
		'#value'		=> 'Submit',
		'#required'		=> TRUE
	);
	$form['register']['result'] = array(
		'#type'			=> 'item',
		'#title'		=> 'Result',
		'#markup'		=> '<pre style="width: 600px;"><div id="register-result"></div></pre>'
	);
	
	return $form;
}

function _osci_tk_users_json_error($error = '') {
	print json_encode(array(
		'success' => FALSE,
		'error' => $error
	));
	drupal_exit();
}

function _osci_tk_users_json_success() {
	print json_encode(array(
		'success' => TRUE,
	));
	drupal_exit();
}