<?php

function osci_tk_epub_menu()
{
	$items = array();
	
	$items['node/%/epub.xhtml'] = array(
		'title' => 'ePub',
		'page callback' => 'osci_tk_epub_render',
		'page arguments' => array(1),
		'access arguments' => array('access content'),
		'type' => MENU_LOCAL_TASK
	);
	
	$items['node/%node/nav.xhtml'] = array(
		'title' => 'ePub Navigation Document',
		'page callback' => 'osci_tk_epub_render_navigation_document',
		'page arguments' => array(1),
		'access arguments' => array('access content'),
		'type' => MENU_LOCAL_TASK
	);		
	
	$items['node/%node/package.opf'] = array(
		'title' => 'ePub Package Document',
		'page callback' => 'osci_tk_epub_render_package_document',
		'page arguments' => array(1),
		'access arguments' => array('access content'),
		'type' => MENU_LOCAL_TASK
	);	
	
	$items['node/%node/%/figure.xhtml'] = array(
		'title' 			=> 'Figure content document',
		'page callback' 	=> 'osci_tk_epub_render_figure_content_document',
		'page arguments'	=> array(1, 2),
		'access arguments' 	=> array('access content'),
		'type' 				=> MENU_CALLBACK,
	);
	return $items;
}


/** 
 * hook_node_insert
 */
function osci_tk_epub_node_insert($node) {

  if (!isset($node->book) || (!$node->book['bid'])) return;
  
  // Pre-generate epub content
  _osci_tk_epub_generate_navigation_document($node);
  _osci_tk_epub_generate_package_document($node);  
  
}


/**
 * hook_node_submit
 */
function osci_tk_epub_node_submit($node, $form, &$form_state)
{
  
  if (isset($node->book) && $node->book['bid']) {
    
    // Clearing the epub caches here will cause the output to be regenerated 
    // even if the node is being removed from the book
    cache_set("osci_epub_package_{$node->book['bid']}", null);     
    cache_set("osci_epub_toc_{$node->book['bid']}", null);  
    
  }
  
}


/** 
 * hook_node_update
 */
function osci_tk_epub_node_update($node) {

  if (!isset($node->book) || (!$node->book['bid'])) return;
  
  // Pre-generate epub content
  _osci_tk_epub_generate_navigation_document($node);
  _osci_tk_epub_generate_package_document($node);    
  
}


function osci_tk_epub_theme($existing, $type, $theme, $path) {
	return array(
		'node__section__epub' => array(
			'template'	=> 'templates/node__section__epub'
		),
		'epub_package' => array(
		    'variables' => array(
		        'pub_id' => null,
		        'title' => null,
		        'language' => 'en',
		        'properties' => array(),
		        'manifest' => array(),
		        'spine' => array()
		    ),
		    'template' => 'templates/epub_package'
		),
		'epub_figure_content_document' => array(
			'template'	=> 'templates/epub_figure_content_document'
		),
		'epub_figure_inline' => array(
			'template'	=> 'templates/epub_figure_inline'
		)
	);
}

// register custom view mode 'epub'
function osci_tk_epub_entity_info_alter(&$entity_info) 
{
	foreach($entity_info as $type => $entity) 
	{
		$entity_info[$type]['view modes']['epub'] = array(
			'label' 			=> t('ePub'),
			'custom settings' 	=> TRUE,
		);
	}
}

function osci_tk_epub_preprocess_node(&$vars) {
	if ($vars['view_mode'] == 'epub') {
		// provide a custom template for nodes by type when view mode is epub
		$vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__epub';
	}
}

function osci_tk_filter_figure_epub() {
	return "this is test text";
}

function osci_tk_epub_render($nid)
{
	global $osci_tk_view_mode;
	
	$osci_tk_view_mode = 'epub';
	
	$node = node_load($nid);
	$view = node_view($node, 'epub');
	print drupal_render($view);
}


/**
 * Render the navigation document for the book corresponding to this node
 */
function osci_tk_epub_render_navigation_document($node)
{

  $dev = false;
  $output = _osci_tk_epub_generate_navigation_document($node, $dev);
  if ($dev) return $output;
  print $output;
  exit();  
  
}


/**
 * Render the package document for the book corresponding to this node
 */
function osci_tk_epub_render_package_document($node)
{

  $dev = false;  
  $output = _osci_tk_epub_generate_package_document($node, $dev);
  if ($dev) return $output;
  
  //header('Content-type: application/oebps-package+xml');
  print $output;
  drupal_exit();
	
}


function osci_tk_epub_render_figure_content_document($section, $fig_index) {
	if ($section->type != 'section') return MENU_NOT_FOUND;
	if (!is_numeric($fig_index)) return MENU_NOT_FOUND;
	
	// prepare the figure from the section's figure field node reference
	$figure = $section->field_figure['und'][$fig_index];
	$figure['node'] = node_load($figure['asset_reference']);
	
	// if this isn't a conservation asset, fake the funk and make it look like
	// it references itself as one
	if ($figure['node']->type != "conservation_asset") {
		$figure['node']->field_assets['und'][0]['nid'] = $figure['node']->nid;
	}
	
	// pass the prepared figure to the theme function which wraps it in 
	// a valid epub3 content document
	$themed_figure = theme('epub_figure_content_document', $figure);
	
	// output the themed figure
	print $themed_figure;
}

function osci_tk_epub_preprocess_epub_figure_content_document(&$vars) {
	// render the conservation asset into markup for the template
	$vars['figure_markup'] = _osci_tk_conservation_get_conservation_html($vars['asset_reference']);
}

function osci_tk_epub_preprocess_epub_figure_inline(&$vars) {
	dpm($vars, 'preprocess epub figure inline');
}

function _osci_tk_epub_check_cache($cache_key) {
  
  // Check static variable    
  $output = &drupal_static($cache_key); 
  if (!is_null($output)) return $output;
  
  // Check cache
  if ($cache = cache_get($cache_key)) {
    $output = $cache->data; // Sets the static variable as well
    return $output;
  }
  
  return null;
  
}


function _osci_tk_epub_generate_navigation_document($node, $no_cache = false) {
  
    // Generate table of contents
    $output = _osci_tk_epub_navigation_generate_book_toc($node, $no_cache);
    
    // Generate other tables...
    
    return $output;
  
}


function _osci_tk_epub_generate_package_document($node, $no_cache = false) {
      // Find the corresponding book for this node
    if (!isset($node->book)) return null;    
    
    /***** Check the cache *****/
    if (!$no_cache) {
      $cache_key = "osci_epub_package_{$node->book['bid']}";    
      $output = _osci_tk_epub_check_cache($cache_key);    
      if (!is_null($output)) {
        print $output; drupal_exit();
      }    
    }
    
    $book = node_load($node->book['bid']);    
    /***** Find all of the resources for this book *****/
    $data = array(
      'modified' => 0,    
      'content_nids' => array(),
      'figures' => array()
    );
    
    $subtree = book_menu_subtree_data($book->book);
    // There should only be one node at the top level
    _osci_tk_epub_package_build_data(array_pop($subtree), $data);        

    // Should this data structure be passed through _osci_tk_epub_package_build_data instead?
    $arguments = array(
        'pub_id' => 'urn:uuid:A1B0D67E-2E81-4DF5-9E67-A64CBE366809',
        'title' => check_plain($book->title),
        'properties' => array(
            'modified' => date(DATE_W3C, $data['modified'])
        ),
        'manifest' => array(),
        'spine' => array()
    );
    
    /***** Build the manifest and spine *****/
    
    // Navigation document
    $arguments['manifest'][] = array(
      'id' => 'nav',
      'href' => url("node/{$node->book['bid']}/nav.xhtml", array('absolute' => true)),
      'media-type' => 'application/xhtml+xml',
      'properties' => 'nav'
    );    
  
    // Content documents go into the manifest and the spine
    foreach($data['content_nids'] as $nid) {
      $id = "section-$nid";
      $arguments['manifest'][] = array(
        'id' => $id,
        'href' => url("node/{$nid}/epub.xhtml", array('absolute' => true)),
        'media-type' => 'application/xhtml+xml',      
      );      
      $arguments['spine'][] = array(
        'idref' => $id,
      );
    }
    
    // Add figures to the manifest
    foreach($data['figures'] as $figure) {
      $arguments['manifest'][] = array(
        'id' => "figure-{$figure['nid']}-{$figure['index']}",
        'href' => url("node/{$figure['nid']}/{$figure['index']}/figure.xhtml", array('absolute' => true)),
        'media-type' => 'application/xhtml+xml',
      );      
    }
    
    // TODO: Additional stuff for the manifest (figures, etc.)    
    
    $output = theme('epub_package', $arguments);
            
    if (!$no_cache) {
      cache_set($cache_key, $output, 'cache');              
    }  
    
    return $output;
  
}


/**
 * Recursively build up the toc metadata for the given book node's subtree
 */
function _osci_tk_epub_navigation_build_toc($tree_node) {
  
  $result = array();

  /*** Build metadata for this node ***/
  if (isset($tree_node['link']['nid'])) {
      $nid = $tree_node['link']['nid'];
  } else {
      $nid = substr($tree_node['link']['href'], strrpos($tree_node['link']['href'], '/') + 1);
  }  
  
  $nextPage = null;
  $prevPage = null;
  $parentPage = null;
  
  if ($tree_node['link']['mlid']) {
      if ($prev = book_prev($tree_node['link'])) {
          $prevPage = substr($prev['href'], strrpos($prev['href'], '/') + 1);
          //$nids[] = $prevPage;
      }
      if ($tree_node['link']['plid'] && $parent = book_link_load($tree_node['link']['plid'])) {
          $parentPage = substr($parent['href'], strrpos($parent['href'], '/') + 1);
          //$nids[] = $parentPage;
      }
      if ($next = book_next($tree_node['link'])) {
          $nextPage = substr($next['href'], strrpos($next['href'], '/') + 1);
          //$nids[] = $nextPage;
      }
  }   
  
  $alias = drupal_lookup_path("alias", $tree_node['link']['href']);
  
  $result['data'] = array(  
	'nid'      => $nid,
  	'mlid'     => $tree_node['link']['mlid'],
  	'title'    => $tree_node['link']['title'],  
    'href'     => url("reader/" . $alias),
    'print'    => url("print/" . $alias),
    'bodycopy' => url($alias['href'] . '/bodycopy'),  
    'next'     => $nextPage,
    'prev'     => $prevPage,
    'parent'   => $parentPage,
    'length'   => 0
  );
  
  if (isset($tree_node['link']['bid'])) {
    $result['data']['bid'] = $tree_node['link']['bid'];
  }
  
  /*** Load additional info from the node ***/
  $result['data'] = array_merge($result['data'], _osci_tk_epub_navigation_node_toc_data($nid));
  
  $result['data']['subtree_length'] = $result['data']['length'];    
  
  /*** Recurse if this node has children ***/
  if (!empty($tree_node['below'])) {
      $result['children'] = array();
      foreach ($tree_node['below'] as $child) {    
        $child_data = _osci_tk_epub_navigation_build_toc($child);   
        $result['children'][] =  $child_data;
        $result['data']['subtree_length'] += $child_data['data']['subtree_length'];
      }
  }  
  
  return $result;  
  
}


/**
 * Gather table of contents data for the given node
 */
function _osci_tk_epub_navigation_node_toc_data($nid) {
  
  $data = array();
  
  $node = node_load($nid);
  
  $data['timestamp'] = $node->changed;  

  if (!empty($node->field_osci_tk_content_length)) {        
    $data['length'] = $node->field_osci_tk_content_length['und'][0]['value'];
  }  

  if (isset($node->field_osci_tk_plate_image['und']) && $node->field_osci_tk_plate_image['und'][0]['nid']) {
    $imageNode = node_load($node->field_osci_tk_plate_image['und'][0]['nid']);
    $fullImageUrl = file_create_url($imageNode->field_image['und'][0]['uri']);
    $thumbnail165Url = image_style_url('osci_tk_default', $imageNode->field_image['und'][0]['uri']);
    $thumbnail100Url = image_style_url('osci_tk_default', $imageNode->field_image['und'][0]['uri']);

    $data['plate_image'] = array(
      'full_image_url' => $fullImageUrl,
      'thumbnail_165w_url' => $thumbnail165Url,
      'thumbnail_100w_url' => $thumbnail100Url
    );
  }    
  
  return $data;
  
}


/**
 * Render the ePub table of contents for the book of the given node
 */
function _osci_tk_epub_navigation_generate_book_toc($node, $no_cache = false)
{
  
  if (!isset($node->book)) return null;  
  
  // Check the cache
  if (!$no_cache) {
    $cache_key = "osci_epub_toc_{$node->book['bid']}";    
    $output = _osci_tk_epub_check_cache($cache_key);
    if (!is_null($output)) {
      return $output;
    }
  }

  // Build the toc for the book
  $toc = null;
  $book = node_load($node->book['bid']);  
  $subtree = book_menu_subtree_data($book->book);
  // There should only be one node at the top level  
  $toc = _osci_tk_epub_navigation_build_toc(array_pop($subtree));

  $output = null;
  
  if (!is_null($toc)) {
          
    // Not using templates for performance. Might consider an XML library.
    $output = "<nav epub:type='toc' id='book-{$node->book['bid']}-toc'>";
    $output .= "<h1>Table of Contents</h1>"; // Optional header
    $output .= "<ol>"; // The only other element allowed as a child of <nav>
    
    /* 
     * The order of li elements contained within the toc nav element must match the order of 
     * the targeted elements within each targeted EPUB Content Document, and must also follow 
     * the order of Content Documents in the Publication spine.
     */
    
    $attr_fields = array('nid', 'mlid', 'length', 'subtree_length', 'editor', 'timestamp');
  
    foreach($toc['children'] as $child) {
      $output .= _osci_tk_epub_navigation_generate_toc_subtree($child, $attr_fields);
    }
      
    $output .= "</ol></nav>";
            
    if (!$no_cache) {
      cache_set($cache_key, $output, 'cache');              
    }
    
  }

  return $output;
    
}


/**
 * Render the ePub table of contents for a node's book subtree
 */
function _osci_tk_epub_navigation_generate_toc_subtree($tree_node, $attr_fields = array()) {

  // Export data fields into html attributes
  $attr_data = array();
  foreach ($attr_fields as $field) {
    if (isset($tree_node['data'][$field])) {
      $attr_data[]= "data-$field='{$tree_node['data'][$field]}'";
    }
    $data_str = count($attr_data) ? join(' ', $attr_data) : '';    
  }    
    
  // <a> points to the target within the EPUB ContentDocument
  $url = url("node/{$tree_node['data']['nid']}/epub.xhtml", array('absolute' => true));
  $content = "<a $data_str href='$url'>{$tree_node['data']['title']}</a>";      

  if (empty($tree_node['children'])) {
    return "<li>$content</li>";
  } 

  $children = '';
  foreach ($tree_node['children'] as $child) {
    $children .= _osci_tk_epub_navigation_generate_toc_subtree($child, $attr_fields);    
  }
  
  // Build children    
  return "<li>$content<ol>$children</ol></li>";    
  
}


/**
 * Recursively collects data to build the package document
 */
function _osci_tk_epub_package_build_data($tree_node, &$data) {
  
    $nid = $tree_node['link']['nid'];
    $node = node_load($nid);
  
    if ($node->changed > $data['modified']) $data['modified'] = $node->changed;
    $data['content_nids'][] = $nid;
    
    if (isset($node->field_figure['und'])) {
      foreach($node->field_figure['und'] as $index => $figure) {
        $data['figures'][] = array(
          'nid' => $nid,
          'index' => $index
        );
      }
    }
  
    /*** Recurse if this node has children ***/
    if (!empty($tree_node['below'])) {
        foreach ($tree_node['below'] as $child) {    
            _osci_tk_epub_package_build_data($child, $data);   
        }
    }  
  
}
